language: generic
sudo: required
services:
  - docker

before_intall:
  - docker build -t matheusboy/travis_docker -f Dockerfile.dev .

script:
  - docker run -e CI=true matheusboy/travis_docker npm run test 