language: generic
sudo: required
services:
  - docker

before_intall:
  - docker build -t matheusboy/Wine_Learning_DevOps -f Dockerfile.dev .

script:
  - docker run -e CI=true matheusboy/Wine_Learning_DevOps npm run test 